version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}  # Contraseña root (segura)
      MYSQL_DATABASE: ${DB_NAME}                # Nombre de tu BD (nodeapi)
      MYSQL_USER: ${DB_USER}                    # Usuario para tu app
      MYSQL_PASSWORD: ${DB_PASSWORD}            # Contraseña del usuario
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql              # Persistencia de datos
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: